### ISSUE TITLE
Automating the building of the website

### ISSUE THREAD

**Issue by pc494** [dsrobertson/onlineFDR#57]
Hi,

I'm hoping to automate the building of the website, following the routine described in: https://www.rostrum.blog/2020/08/09/ghactions-pkgs/

Is there anything weird going on with the way the website currently works that I should be aware of?

Best wishes,
Phillip Crout

**Comment by latlio** [comment]
Hi Phillip, I'm not sure what you mean by "anything weird". Also, can you clarify what you mean by "automate the building" -- is this for our pkgdown vignette?

**Comment by pc494** [comment]
> Hi Phillip, I'm not sure what you mean by "anything weird". 

"weird" as in customization that I might not expect. At first glance I think the answer is no.

> Also, can you clarify what you mean by "automate the building" -- is this for our pkgdown vignette?

Yes, I think so. I was hoping to automating the building of the website so that the version that appears online (at https://dsrobertson.github.io/onlineFDR/) is live to the current code. The simplest way to do this (as far as I could tell) is to integrate with github, either directly or via actions.

**Comment by latlio** [comment]
I don't think there should be anything majorly weird with the website itself (we just used pkgdown out of the box for the most part) if I remember correctly! David -- there may have been an issue with rendering of ggplot2, right?

**Comment by pc494** [comment]
Okay, think I've got this (sort of working), will loop back to it next week and submit a PR, in the meantime the current (forked) failing build can be found at: https://github.com/pc494/onlineFDR/runs/5250883704?check_suite_focus=true

**Comment by dsrobertson** [comment]
Thanks a lot Phillip! Just to confirm, as far as I'm aware there's nothing 'weird' with the website itself. Lathan -- I removed the parts of the vignette that relied on ggplot2.

**Comment by pc494** [comment]
Okay, I think I've now got the action part of the workflow going correctly, but the build is failing for website related reasons. I'm going to bundle those changes with the addition of BioC testing into a single PR. It would be really helpful if one/both of you could eyeball the pkgdown error and point me in the right direction as I'm fairly new to this bit of technology.
