### ISSUE TITLE
Error when using batch version of SAFFRONstar

### ISSUE THREAD

**Issue by aaronjfisher** [dsrobertson/onlineFDR#60]
The example in the documentation for SAFFRONstar with version == 'batch' works fine, but if I replace it with a p-value vector of random uniforms, with equal length, I get an error.

```R

## Example from documentation works fine
pval_predefined = c(2.90e-08, 0.06743, 0.01514, 0.08174, 0.00171,
        3.60e-05, 0.79149, 0.27201, 0.28295, 7.59e-08,
        0.69274, 0.30443, 0.00136, 0.72342, 0.54757)
SAFFRONstar(data.frame(pval= pval_predefined), 
    version='batch', batch.sizes = c(4,6,5))


## Using random p-values generates an error
set.seed(0)
L <- length(pval_predefined)
pval_random <- runif(L)
SAFFRONstar(data.frame(pval= pval_random), 
    version='batch', batch.sizes = c(4,6,5))
    
   ## Error in data.frame(pval, batch = batch.no, alphai, R) : 
   ## arguments imply differing number of rows: 15, 8
```

As far as I can tell, there shouldn't be any meaningful difference between these two vectors that would have caused this. Is there?

```R
length(pval_predefined) == length(pval_random)
class(pval_predefined)  == class(pval_random)
```

**Comment by aaronjfisher** [comment]
Hm, actually this issue only happens for me using the version of the package on Bioconductor. If I install from github, it works fine. That's a little confusing since the Bioconductor version is 2.4.0, which is later than the github version of 2.1.2. Is there a version tracking issue there? Leaving this open for now to flag the possible Bioconductor issue, although it seems to be fixed for me, and could be something about my setup. 

Thanks!!

**Comment by dsrobertson** [comment]
I've pushed the latest changes from GitHub to the development version of the package on Bioconductor, so the issue should be solved if you install it from the latter. The release version of the package on Bioconductor will be automatically updated in the next release cycle in October.
